/**
 * App icon aliases backed by Lucide's standard, maintained web icon set.
 * Keeping the local names gives the app one stable import surface while
 * avoiding bespoke SVG paths.
 */
export {
  ArrowDown as DownIcon,
  ArrowUp as UpIcon,
  ChartNoAxesColumnIncreasing as StatsIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  Clock3 as ClockIcon,
  Compass as CompassIcon,
  Copy as CopyIcon,
  Download as DownloadIcon,
  EllipsisVertical as EllipsisIcon,
  Folder as FolderIcon,
  Globe as GlobeIcon,
  GripVertical as GripIcon,
  Headphones as HeadphonesIcon,
  Link as ShareIcon,
  ListMusic as QueueIcon,
  ListStart as PlayNextIcon,
  LoaderCircle as LoaderIcon,
  Lock as LockIcon,
  LogOut as LogoutIcon,
  Music2 as MusicIcon,
  Pause as PauseIcon,
  Pencil as PencilIcon,
  Play as PlayIcon,
  Plus as PlusIcon,
  RefreshCw as RefreshIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Shuffle as ShuffleIcon,
  SkipBack as PrevIcon,
  SkipForward as NextIcon,
  Trash2 as TrashIcon,
  Users as UsersIcon,
  Volume2 as VolumeIcon,
  Waypoints as SimilarIcon,
  X as XIcon,
} from "lucide-react";
